### ISSUE TITLE
[request] Have an A+AAAA type

### ISSUE THREAD

**Issue by guysoft** [anaganisk/digitalocean-dynamic-dns-ip#12]
Hey,
I was wondering if it would make sense to create a type for both A and AAAA domains, since all my domains have both entries, and it creates a large duplication. 

You could also just expand the json each time and then just handle this in the configuration loading and not in the actual dns update code. After [the json.Unmarshal comand here]( https://github.com/anaganisk/digitalocean-dynamic-dns-ip/blob/master/digitalocean-dynamic-ip.go#L100)

**Comment by johnjaylward** [comment]
I'm not sure what you are asking for. can you elaborate, or give an example of the configuration you are looking for?

**Comment by anaganisk** [comment]
@guysoft hey I'm not really sure what you are asking for here, more details could help.

**Comment by guysoft** [comment]
The issue is that I have to enter all entries twice. One A and one AAAA entry.

SO was thinking that instead for for example:

```json
{
  "apikey": "****",
  "doPageSize": 20,
  "useIPv4": true,
  "useIPv6": true,
  "ipv4CheckUrl": "https://ipv4bot.whatismyipaddress.com",
  "ipv6CheckUrl": "https://ipv6bot.whatismyipaddress.com",
  "allowIPv4InIPv6": false,
  "domains": [
    {
      "domain": "hayu.sh",
      "records": [
        {
          "name": "@",
          "type": "A"
        },
        {
          "name": "@",
          "type": "AAAA"
        }
      ]
    }
  ]
}
 ```

You could have a type that is both A and AAAA updates:

```json
{
  "apikey": "****",
  "doPageSize": 20,
  "useIPv4": true,
  "useIPv6": true,
  "ipv4CheckUrl": "https://ipv4bot.whatismyipaddress.com",
  "ipv6CheckUrl": "https://ipv6bot.whatismyipaddress.com",
  "allowIPv4InIPv6": false,
  "domains": [
    {
      "domain": "hayu.sh",
      "records": [
        {
          "name": "@",
          "type": "A+AAAA"
        }
      ]
    }
  ]
}
```

I was suggesting where also the addition would go, right after parsing the json file. That would mean that you just write one function that expands the type to two. And then the code runs normally.

**Comment by anaganisk** [comment]
@guysoft I see what you mean but, right now the JSON structure is clear and readable, adding this feature may solve some rare cases as yours but the JSON would not be clear to understand anymore(A+AAAA for type). I will close this issue for now, but will may be think of adding it when we might have a better way to describe multiple types in JSON

**Comment by guysoft** [comment]
Cool, another suggestion would be ti have type or types and accept a list and not a string.
