### ISSUE TITLE
url.PathScape error when building

### ISSUE THREAD

**Issue by deftoner** [anaganisk/digitalocean-dynamic-dns-ip#5]
Hello there! thanks for your work. I was trying to just do the build of your script for two hours now. :(

First install go, then downloading dependences (go-homedir package....), now after all that, I get this error:
./digitalocean-dynamic-ip.go:177: undefined: url.PathEscap
./digitalocean-dynamic-ip.go:269: undefined: url.PathEscape

Its an ubuntu server 18 almost clean install

**Comment by johnjaylward** [comment]
the url.PathEscape should be available in go 1.8 or higher. can you confirm your installed version:
`go version` ?

**Comment by deftoner** [comment]
That was the issue, Thanks!
