### ISSUE TITLE
Push notif support for IP address changes

### ISSUE THREAD

**Issue by johnjaylward** [anaganisk/digitalocean-dynamic-dns-ip#9]
As noted in #8, some people would like to receive notifications if their IP changed. I think the easiest way would be to do email as most phone companies have an email interface for SMS/MMS messages (i.e. `1239535875@txt.att.net` : https://www.textsendr.com/emailsms.php )

**Comment by anaganisk** [comment]
@johnjaylward How about twilio integration instead since, In my country(India) no such interface is provided.
